#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jul 18 13:37:10 2018

@author: ninja1mmm
"""
import os
import numpy as np
import pandas as pd
from sklearn import preprocessing

def file_name(file_dir):   
    root_tmp=[]
    dirs_tmp=[]
    files_tmp=[]
    for root, dirs, files in os.walk(file_dir):  
        root_tmp.append(root)
        dirs_tmp.append(dirs)
        files_tmp.append(files)
    return root_tmp, dirs_tmp, files_tmp
        
        
root = '/home/ninja1mmm/Desktop/phm/data'
root_tmp, dirs_tmp, files_tmp = file_name(root)

combined_all = {}
feature_all = {}

# read the first file to test here
file_tmp = files_tmp[2][0]
# iterate through the files if needed
#for file_tmp in files_tmp[2]:
    
path_tmp = root_tmp[2]+'/'+file_tmp
df = pd.read_pickle(path_tmp)
#------------------------------------------------------------------------------
# Crucial step
df=df.replace([np.inf, -np.inf], np.nan).dropna()
df=df.reset_index(drop=True)
df_scaler = preprocessing.MinMaxScaler(feature_range = (0,1))

#------------------------------------------------------------------------------
lot_list = list(set(df.Lot))
# Check if Lot already existed
for key in lot_list:
    if key in combined_all.keys():
        print('The Lot %d already existed in %s' % (key, file_tmp))
        
#for tmp in lot_list:
#    combined_all[tmp] = []
# Select and save all the wafer processing cycles
list_tmp = []
lot_last = df.Lot[0]
counter = 0
# Specify the range. Here set to 100000 for the ease of test
for row_tmp in df.index[0:10000]:
    lot_tmp = df.iloc[row_tmp,:].Lot
    if lot_tmp == lot_last:
        list_tmp.append(df.iloc[row_tmp,:])
        counter += 1
    else:
        df_tmp = pd.concat(list_tmp, axis = 1)
        # lot_last serves as the key, can be changed 
#        combined_all[lot_last] = df_tmp.T
        combined_all[df_tmp.T.time.iloc[-1]] = df_tmp.T
        # Calculate mean and save in feature dictionary as an example
        # Normalize the data again because for some parameters we need the local (within cycle) feature
        feature_tmp = df_tmp.T.iloc[:,7:] # Not a correct way, because shutter position also need to be excluded
        feature_tmp = df_scaler.fit_transform(feature_tmp)
        feature_all[df_tmp.T.time.iloc[-1]] = np.mean(feature_tmp)
        
        
        list_tmp = []
        counter = 0
    lot_last = lot_tmp
    
    
    
    
#------------------------------------------------------------------------------





